---
#defaultBaseImage: cgr.dev/chainguard/glibc-dynamic:latest
defaultBaseImage: ghcr.io/kcl-lang/kcl:v0.12.3
builds:
  - id: claim-machinery-api
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
