---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  lint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/linting.yaml
  go:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/lint.yaml
  dagger:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/dagger/modules.yaml

vars:
  DATE:
    sh: date +"%y.%m%d.%H%M"
  PROJECT:
    sh: |
      basename $(pwd)
  DAGGER_MOUDLE_DIR: ./.dagger
  SOURCE_CODE_DIR: "."
  BIN_EXPORT_PATH: /tmp/go/build/{{ .PROJECT }}
  TEMPLATES_DIR: internal/claimtemplate/testdata
  TEMPLATE_PROFILE_PATH: tests/profile.yaml
  DAGGER_KCL_MODULE: github.com/stuttgart-things/dagger/kcl@v0.74.0
  DEPLOYMENT_SOURCE_DIR: deployment
  KCL_PROFILE_FILE: tests/kcl-deploy-profile.yaml
  RENDERED_OUTPUT_PATH: /tmp/rendered-{{ .PROJECT }}.yaml

tasks:
  lint:
    desc: Run Go lint via Dagger module
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} lint \
          --src "{{ .SOURCE_CODE_DIR }}" \
          --progress plain

  build-test-api:
    desc: Build and test api
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-and-test \
        --src "{{ .SOURCE_CODE_DIR }}" \
        --progress plain -vv

  build-push-image-kcl:
    desc: Build and push container image with KCL build module
    vars:
      DEV_IMAGE_DESTINATION: "ttl.sh/sthings/claim-machinery-api"
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-image-with-kcl \
        --source "{{ .SOURCE_CODE_DIR }}" \
        --repo "{{ .DEV_IMAGE_DESTINATION }}:{{ .DATE }}" \
        --push=true \
        --progress plain -vv

  build-scan-image-kcl:
    desc: Build, push and scan container image with KCL build module
    cmds:
      - |
        RANDOM_TAG=$(openssl rand -hex 6)
        IMAGE_REF="ttl.sh/{{ .PROJECT }}-${RANDOM_TAG}:latest"

        echo "ðŸ”¨ Building with KCL and pushing to: ${IMAGE_REF}"
        echo ""

        # Build and push with KCL build module
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-image-with-kcl \
          --source "{{ .SOURCE_CODE_DIR }}" \
          --repo "$IMAGE_REF" \
          --push="true" \
          --progress plain

        echo ""
        echo "âœ… Image pushed: $IMAGE_REF"
        echo ""
        echo "ðŸ” Scanning with Trivy..."
        echo ""

        # Export scan report
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "$IMAGE_REF" \
          --severity "HIGH,CRITICAL" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Build and scan complete!"
        echo "ðŸ“¦ Image: $IMAGE_REF"
        echo "ðŸ“¦ Pull: docker pull $IMAGE_REF"
        echo "ðŸ“„ Scan Report: /tmp/trivy-scan-{{ .PROJECT }}.json"
        echo "â° Expires: 1 hour (default ttl.sh)"

        # Show summary
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No HIGH/CRITICAL vulnerabilities found!"
        fi

  build-output-binary:
    desc: Build project binary
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build \
        --src "{{ .SOURCE_CODE_DIR }}" \
        --bin-name="{{ .PROJECT }}" \
        --progress plain -vv \
        export --path={{ .BIN_EXPORT_PATH }}

        ls -lta {{ .BIN_EXPORT_PATH }}
        du -sh {{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}

        # Pretty summary for the user
        BIN_FILE="{{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}"
        SIZE=$(du -sh "$BIN_FILE" | awk '{print $1}')
        SHASUM=$(sha256sum "$BIN_FILE" | awk '{print $1}')

        BLUE='\033[1;34m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        NC='\033[0m'

        echo -e "${BLUE}==============================================${NC}"

  build-scan-image-ko:
    desc: Build, push and scan container image
    cmds:
      - |
        RANDOM_TAG=$(openssl rand -hex 6)
        REPO_NAME="ttl.sh/{{ .PROJECT }}-${RANDOM_TAG}"

        echo "ðŸ”¨ Building and pushing to: ${REPO_NAME}"
        echo ""

        # Build and push directly to ttl.sh (no auth needed)
        IMAGE_REF=$(dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-image \
          --src "{{ .SOURCE_CODE_DIR }}" \
          --repo "$REPO_NAME" \
          --push="true" \
          --scan="true" \
          --scan-severity="HIGH,CRITICAL" \
          --progress plain)

        echo ""
        echo "âœ… Image pushed: $IMAGE_REF"
        echo ""
        echo "ðŸ” Generating scan report..."
        echo ""

        # Export scan report
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "$IMAGE_REF" \
          --severity "HIGH,CRITICAL" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Build and scan complete!"
        echo "ðŸ“¦ Image: $IMAGE_REF"
        echo "ðŸ“¦ Pull: docker pull $IMAGE_REF"
        echo "ðŸ“„ Scan Report: /tmp/trivy-scan-{{ .PROJECT }}.json"
        echo "â° Expires: 1 hour (default ttl.sh)"

        # Show summary
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No HIGH/CRITICAL vulnerabilities found!"
        fi

  scan-image-interactive:
    desc: Scan container image for vulnerabilities with Trivy (interactive prompts)
    vars:
      IMAGE_REF:
        sh: 'gum input --placeholder "Enter image reference (e.g., ttl.sh/my-app:latest)" --header "IMAGE TO SCAN"'
      SEVERITY:
        sh: 'gum input --placeholder "Severity levels" --value "HIGH,CRITICAL" --header "SEVERITY"'
    cmds:
      - |
        echo ""
        echo "ðŸ” Scanning image: {{ .IMAGE_REF }}"
        echo "âš ï¸  Severity: {{ .SEVERITY }}"
        echo ""

        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "{{ .IMAGE_REF }}" \
          --severity "{{ .SEVERITY }}" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Scan complete!"
        echo "ðŸ“„ Report: /tmp/trivy-scan-{{ .PROJECT }}.json"

        # Show summary if jq is available
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No vulnerabilities found!"
        fi

  scan-image:
    desc: Scan container image for vulnerabilities with Trivy (non-interactive, vars only)
    vars:
      IMAGE_REF: '{{ .IMAGE_REF | default "ttl.sh/example:latest" }}'
      SEVERITY: '{{ .SEVERITY | default "HIGH,CRITICAL" }}'
    cmds:
      - |
        echo ""
        echo "ðŸ” Scanning image: {{ .IMAGE_REF }}"
        echo "âš ï¸  Severity: {{ .SEVERITY }}"
        echo ""

        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "{{ .IMAGE_REF }}" \
          --severity "{{ .SEVERITY }}" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Scan complete!"
        echo "ðŸ“„ Report: /tmp/trivy-scan-{{ .PROJECT }}.json"

        # Show summary if jq is available
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No vulnerabilities found!"
        fi

  run-local-go:
    desc: Run API locally with go run (flags supported)
    cmds:
      - |
        set -e
        FLAGS="--templates-dir {{ .TEMPLATES_DIR }}"
        if [ -n "{{ .TEMPLATE_PROFILE_PATH }}" ]; then
          FLAGS="$FLAGS --template-profile-path {{ .TEMPLATE_PROFILE_PATH }}"
        fi
        echo "Running: go run main.go $FLAGS"
        go run main.go $FLAGS

  run-local-bin:
    desc: Run exported binary locally (flags supported)
    deps: [build-output-binary]
    cmds:
      - |
        set -e
        BIN_FILE="{{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}"
        if [ ! -x "$BIN_FILE" ]; then
          echo "Binary not found at $BIN_FILE. Run 'task build-output-binary' first." >&2
          exit 1
        fi
        FLAGS="--templates-dir {{ .TEMPLATES_DIR }}"
        if [ -n "{{ .TEMPLATE_PROFILE_PATH }}" ]; then
          FLAGS="$FLAGS --template-profile-path {{ .TEMPLATE_PROFILE_PATH }}"
        fi
        echo "Running: PORT=8080 $BIN_FILE $FLAGS"
        PORT=8080 "$BIN_FILE" $FLAGS

  render-manifests:
    desc: Render Kubernetes manifests using KCL via Dagger
    vars:
      SOURCE:
        sh: 'gum input --placeholder "Source directory" --value "{{ .DEPLOYMENT_SOURCE_DIR }}" --header "KCL SOURCE DIRECTORY"'
      PROFILE:
        sh: 'gum input --placeholder "Profile file path" --value "{{ .KCL_PROFILE_FILE }}" --header "PARAMETERS FILE"'
      DESTINATION:
        sh: 'gum input --placeholder "Output path" --value "{{ .RENDERED_OUTPUT_PATH }}" --header "OUTPUT PATH"'
    cmds:
      - |
        echo ""
        echo "ðŸ”¨ Rendering manifests with KCL..."
        echo "ðŸ“‚ Source: {{ .SOURCE }}"
        echo "ðŸ“„ Profile: {{ .PROFILE }}"
        echo "ðŸ“¦ Output: {{ .DESTINATION }}"
        echo ""

        dagger call -m {{ .DAGGER_KCL_MODULE }} run \
          --source "{{ .SOURCE }}" \
          --parameters-file="{{ .PROFILE }}" \
          export --path="{{ .DESTINATION }}"

        echo ""
        echo "âœ… Manifests rendered successfully!"
        echo "ðŸ“„ Output file: {{ .DESTINATION }}"
        echo ""

        # Show preview if file exists
        if [ -f "{{ .DESTINATION }}" ]; then
          echo "ðŸ“‹ Preview:"
          head -n 20 "{{ .DESTINATION }}"
          echo ""
          echo "... (use 'cat {{ .DESTINATION }}' to view full file)"
        fi

  render-manifests-quick:
    desc: Render Kubernetes manifests (non-interactive, uses defaults)
    vars:
      SOURCE: '{{ .SOURCE | default .DEPLOYMENT_SOURCE_DIR }}'
      PROFILE: '{{ .PROFILE | default .KCL_PROFILE_FILE }}'
      DESTINATION: '{{ .DESTINATION | default .RENDERED_OUTPUT_PATH }}'
    cmds:
      - |
        echo ""
        echo "ðŸ”¨ Rendering manifests with KCL..."
        echo "ðŸ“‚ Source: {{ .SOURCE }}"
        echo "ðŸ“„ Profile: {{ .PROFILE }}"
        echo "ðŸ“¦ Output: {{ .DESTINATION }}"
        echo ""

        dagger call -m {{ .DAGGER_KCL_MODULE }} run \
          --source "{{ .SOURCE }}" \
          --parameters-file="{{ .PROFILE }}" \
          export --path="{{ .DESTINATION }}"

        echo ""
        echo "âœ… Manifests rendered successfully!"
        echo "ðŸ“„ Output file: {{ .DESTINATION }}"

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
