---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  lint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/linting.yaml
  go:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/lint.yaml
  dagger:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/dagger/modules.yaml

vars:
  PROJECT:
    sh: |
      basename $(pwd)
  DAGGER_MOUDLE_DIR: ./.dagger
  SOURCE_CODE_DIR: "."
  BIN_EXPORT_PATH: /tmp/go/build/{{ .PROJECT }}
  TEMPLATES_DIR: internal/claimtemplate/testdata
  TEMPLATE_PROFILE_PATH: tests/profile.yaml

tasks:
  lint:
    desc: Run Go lint via Dagger module
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} lint \
          --src "{{ .SOURCE_CODE_DIR }}" \
          --progress plain

  build-test-api:
    desc: Build and test api
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-and-test \
        --src "{{ .SOURCE_CODE_DIR }}" \
        --progress plain -vv

  build-output-binary:
    desc: Build project binary
    cmds:
      - |
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} build \
        --src "{{ .SOURCE_CODE_DIR }}" \
        --bin-name="{{ .PROJECT }}" \
        --progress plain -vv \
        export --path={{ .BIN_EXPORT_PATH }}

        ls -lta {{ .BIN_EXPORT_PATH }}
        du -sh {{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}

        # Pretty summary for the user
        BIN_FILE="{{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}"
        SIZE=$(du -sh "$BIN_FILE" | awk '{print $1}')
        SHASUM=$(sha256sum "$BIN_FILE" | awk '{print $1}')

        BLUE='\033[1;34m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        NC='\033[0m'

        echo -e "${BLUE}==============================================${NC}"

  build-scan-image:
    desc: Build, push and scan container image
    cmds:
      - |
        RANDOM_TAG=$(openssl rand -hex 6)
        REPO_NAME="ttl.sh/{{ .PROJECT }}-${RANDOM_TAG}"

        echo "ðŸ”¨ Building and pushing to: ${REPO_NAME}"
        echo ""

        # Build and push directly to ttl.sh (no auth needed)
        IMAGE_REF=$(dagger call -m {{ .DAGGER_MOUDLE_DIR }} build-image \
          --src "{{ .SOURCE_CODE_DIR }}" \
          --repo "$REPO_NAME" \
          --push="true" \
          --scan="true" \
          --scan-severity="HIGH,CRITICAL" \
          --progress plain)

        echo ""
        echo "âœ… Image pushed: $IMAGE_REF"
        echo ""
        echo "ðŸ” Generating scan report..."
        echo ""

        # Export scan report
        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "$IMAGE_REF" \
          --severity "HIGH,CRITICAL" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Build and scan complete!"
        echo "ðŸ“¦ Image: $IMAGE_REF"
        echo "ðŸ“¦ Pull: docker pull $IMAGE_REF"
        echo "ðŸ“„ Scan Report: /tmp/trivy-scan-{{ .PROJECT }}.json"
        echo "â° Expires: 1 hour (default ttl.sh)"

        # Show summary
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No HIGH/CRITICAL vulnerabilities found!"
        fi

  scan-image-interactive:
    desc: Scan container image for vulnerabilities with Trivy (interactive prompts)
    vars:
      IMAGE_REF:
        sh: 'gum input --placeholder "Enter image reference (e.g., ttl.sh/my-app:latest)" --header "IMAGE TO SCAN"'
      SEVERITY:
        sh: 'gum input --placeholder "Severity levels" --value "HIGH,CRITICAL" --header "SEVERITY"'
    cmds:
      - |
        echo ""
        echo "ðŸ” Scanning image: {{ .IMAGE_REF }}"
        echo "âš ï¸  Severity: {{ .SEVERITY }}"
        echo ""

        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "{{ .IMAGE_REF }}" \
          --severity "{{ .SEVERITY }}" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Scan complete!"
        echo "ðŸ“„ Report: /tmp/trivy-scan-{{ .PROJECT }}.json"

        # Show summary if jq is available
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No vulnerabilities found!"
        fi

  scan-image:
    desc: Scan container image for vulnerabilities with Trivy (non-interactive, vars only)
    vars:
      IMAGE_REF: '{{ .IMAGE_REF | default "ttl.sh/example:latest" }}'
      SEVERITY: '{{ .SEVERITY | default "HIGH,CRITICAL" }}'
    cmds:
      - |
        echo ""
        echo "ðŸ” Scanning image: {{ .IMAGE_REF }}"
        echo "âš ï¸  Severity: {{ .SEVERITY }}"
        echo ""

        dagger call -m {{ .DAGGER_MOUDLE_DIR }} scan-image \
          --image-ref "{{ .IMAGE_REF }}" \
          --severity "{{ .SEVERITY }}" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT }}.json

        echo ""
        echo "âœ… Scan complete!"
        echo "ðŸ“„ Report: /tmp/trivy-scan-{{ .PROJECT }}.json"

        # Show summary if jq is available
        if command -v jq &> /dev/null; then
          echo ""
          echo "ðŸ“Š Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT }}.json 2>/dev/null || echo "âœ… No vulnerabilities found!"
        fi

  run-local-go:
    desc: Run API locally with go run (flags supported)
    cmds:
      - |
        set -e
        FLAGS="--templates-dir {{ .TEMPLATES_DIR }}"
        if [ -n "{{ .TEMPLATE_PROFILE_PATH }}" ]; then
          FLAGS="$FLAGS --template-profile-path {{ .TEMPLATE_PROFILE_PATH }}"
        fi
        echo "Running: go run main.go $FLAGS"
        go run main.go $FLAGS

  run-local-bin:
    desc: Run exported binary locally (flags supported)
    deps: [build-output-binary]
    cmds:
      - |
        set -e
        BIN_FILE="{{ .BIN_EXPORT_PATH }}/{{ .PROJECT }}"
        if [ ! -x "$BIN_FILE" ]; then
          echo "Binary not found at $BIN_FILE. Run 'task build-output-binary' first." >&2
          exit 1
        fi
        FLAGS="--templates-dir {{ .TEMPLATES_DIR }}"
        if [ -n "{{ .TEMPLATE_PROFILE_PATH }}" ]; then
          FLAGS="$FLAGS --template-profile-path {{ .TEMPLATE_PROFILE_PATH }}"
        fi
        echo "Running: PORT=8080 $BIN_FILE $FLAGS"
        PORT=8080 "$BIN_FILE" $FLAGS
  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
