---
name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-go-microservice-release.yaml@main
    with:
      runs-on: ubuntu-latest
      source-image: ghcr.io/stuttgart-things/claim-machinery-api:main
      target-image-repo: ghcr.io/stuttgart-things/claim-machinery-api
      kcl-source-dir: deployment
      kcl-profile-file: tests/kcl-deploy-profile.yaml
      kustomize-oci-repo: ghcr.io/stuttgart-things/claim-machinery-api-kustomize
    secrets: inherit
